### ISSUE TITLE
大佬字节青训组我一个？

### ISSUE THREAD

**Issue by huyiyuezz** [zyyv/zyyv#1]
比较菜，vue2.0，react类组件在公司开发了半年，已经大四了，目前没有好项目，想写一个好点的项目（方便面试吹水），es6，js功底不能算太差。

**Comment by zyyv** [comment]
> 比较菜，vue2.0，react类组件在公司开发了半年，已经大四了，目前没有好项目，想写一个好点的项目（方便面试吹水），es6，js功底不能算太差。

不好意思，队伍组满了。😥

**Comment by huyiyuezz** [comment]
好吧

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月14日(周五) 晚上10:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [chris-zhu/chris-zhu] 大佬字节青训组我一个？ (Issue #1)




  
比较菜，vue2.0，react类组件在公司开发了半年，已经大四了，目前没有好项目，想写一个好点的项目（方便面试吹水），es6，js功底不能算太差。
  
不好意思，队伍组满了。😥
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
